{{- if not .Values.apiserver.serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}-apiserver
{{- end }}
---
{{- if not .Values.controller.serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}-controller
{{- end }}
