# We 'require' the code-generators listed here so that dep vendors them for us.
# Whilst we don't directly depend on any code in k8s.io/code-generator, the
# repository is required in order to use ./hack/update-codegen.sh.
required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/lister-gen",
]


# gengo needs to be manually pinned to the version listed in code-generators
# Gopkg.toml, because the k8s project does not produce Gopkg.toml files & dep
# does not parse the Godeps.json file to determine revisions to use.
[[override]]
  name = "k8s.io/gengo"
  revision = "9e661e9308f078838e266cca1c673922088c0ea4"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/mitsuse/pushbullet-go"
  version = "0.1.0"

# Kubernetes dependency pinning
[[constraint]]
  branch = "release-1.8"
  name = "k8s.io/apimachinery"

[[constraint]]
  branch = "release-1.8"
  name = "k8s.io/api"

[[constraint]]
  branch = "release-1.8"
  name = "k8s.io/apiserver"

[[constraint]]
  branch = "release-1.8"
  name = "k8s.io/code-generator"

[[constraint]]
  name = "k8s.io/client-go"
  version = "^5.0.0"
